from django.conf.urls import *
from django.conf import settings
from . import views
from .isatab import ISATabExportView, isa_study_view

urlpatterns = [
    url(r'^populate_select/(?P<model>\w+)/(?P<key>\w+)[/]*$', views.populate_select),
    url(r'^populate_select/(?P<model>\w+)/(?P<key>\w+)/(?P<value>\w+)[/]*$', views.populate_select),
    url(r'^populate_select/(?P<model>\w+)/(?P<key>\w+)/(?P<value>\w+)/(?P<field>\w+)/(?P<match>\w+)[/]*$', views.populate_select),
    url(r'^records/(?P<model>\w+)/(?P<field>\w+)/(?P<value>.+)[/]*$', views.records),
    url(r'^create/(?P<model>\w+)[/]*$', views.create_object),
    url(r'^createSamples[/]*$', views.create_samples),
    url(r'^batchcreate/samplelog[/]*$', views.batch_create_sample_logs),
    url(r'^update/(?P<model>\w+)/(?P<id>\w+)[/]*$', views.update_object),
    url(r'^delete/(?P<model>\w+)/(?P<id>\w+)[/]*$', views.delete_object),
    url(r'^associate/(?P<model>\w+)/(?P<association>\w+)/(?P<parent_id>\w+)/(?P<id>\w+)[/]*$', views.associate_object),
    url(r'^dissociate/(?P<model>\w+)/(?P<association>\w+)/(?P<parent_id>\w+)/(?P<id>\w+)[/]*$', views.dissociate_object),
    url(r'^recreate_sample_classes/(?P<experiment_id>\w+)[/]*$', views.recreate_sample_classes),
    url(r'^recordsProject/(?P<project_id>\w+)[/]*$', views.recordsProject),
    url(r'^recordsExperiments[/]*$', views.recordsExperiments),
    url(r'^recordsExperiments/(?P<project_id>\w+)[/]*$', views.recordsExperimentsForProject),
    url(r'^recordsRuns[/]*$', views.recordsRuns),
    url(r'^recordsRuleGenerators[/]*$', views.recordsRuleGenerators),
    url(r'^recordsRuleGeneratorsAccessibility[/]*$', views.recordsRuleGeneratorsAccessibility),
    url(r'^recordsRuleGeneratorsAccessibilityEnabled[/]*$', views.recordsRuleGeneratorsAccessibilityEnabled),
    url(r'^recordsSamplesForExperiment[/]*$', views.recordsSamplesForExperiment),
    url(r'^recordsSamplesForRun[/]*$', views.recordsSamplesForRun),
    url(r'^recordsMAStaff[/]*$', views.recordsMAStaff),
    url(r'^recordsClientList[/]*$', views.recordsClientList),
    url(r'^recordsClientFiles[/]*$', views.recordsClientFiles),
    url(r'^recordsSamples/experiment__id/(?P<experiment_id>\w+)[/]*$', views.recordsSamples),
    url(r'^recordsSamplesForClient/client/(?P<client>.+)[/]*$', views.recordsSamplesForClient),
    url(r'^recordsComponents[/]*$', views.recordsComponents),
    url(r'^recent_projects[/]*$', views.recent_projects),
    url(r'^recent_experiments[/]*$', views.recent_experiments),
    url(r'^recent_runs[/]*$', views.recent_runs),
    url(r'^sample_class_enable/(?P<id>\w+)[/]*$', views.sample_class_enable),
    url(r'^files[/]*$', views.experimentFilesList),
    url(r'^runFiles[/]*$', views.runFilesList),
    url(r'^moveFile[/]*$', views.moveFile),
    url(r'^deleteFile[/]*$', views.deleteFile),
    url(r'^uploadFile[/]*$', views.uploadFile),
    url(r'^newFolder[/]*$', views.newFolder),
    url(r'^uploadSampleCSV[/]*$', views.CSVUploadViewFile.as_view()),
    url(r'^uploadRunCaptureCSV[/]*$', views.CSVUploadViewCaptureCSV.as_view()),
    url(r'^packageFilesForDownload[/]*$', views.packageFilesForDownload),
    url(r'^downloadPackage[/]*$', views.downloadPackage),
    url(r'^downloadFile[/]*$', views.downloadFile),
    url(r'^downloadClientFile/(?P<filepath>.+)$', views.downloadClientFile),
    url(r'^downloadSOPFileById/(?P<sop_id>\w+)[/]*$', views.downloadSOPFileById),
    url(r'^downloadSOPFile/(?P<sop_id>\w+)/(?P<filename>.*)[/]*$', views.downloadSOPFile, name='downloadSOPFile'),
    url(r'^downloadRunFile[/]*$', views.downloadRunFile),
    url(r'^shareFile[/]*$', views.shareFile),
    url(r'^updateSingleSource/(?P<exp_id>\w+)[/]*$', views.update_single_source),
    url(r'^generate_worklist/(?P<run_id>\w+)[/]*$', views.generate_worklist, name='generate_worklist'),
    url(r'^display_worklist/(?P<run_id>\w+)[/]*$', views.display_worklist, name='display_worklist'),
    url(r'^mark_run_complete/(?P<run_id>\w+)[/]*$', views.mark_run_complete, name='mark_run_complete'),
    url(r'^add_samples_to_run[/]*$', views.add_samples_to_run, name='add_samples_to_run'),
    url(r'^add_samples_to_class[/]*$', views.add_samples_to_class, name='add_samples_to_class'),
    url(r'^report_error[/]*$', views.report_error, name='report_error'),
    url(r'^remove_samples_from_run[/]*$', views.remove_samples_from_run, name='remove_samples_from_run'),
    url(r'^get_rule_generator[/]*$', views.get_rule_generator, name='get_rule_generator'),
    url(r'^create_rule_generator[/]*$', views.create_rule_generator, name='create_rule_generator'),
    url(r'^edit_rule_generator[/]*$', views.edit_rule_generator, name='edit_rule_generator'),
    url(r'^clone_rule_generator[/]*$', views.clone_rule_generator, name='clone_rule_generator'),
    url(r'^create_new_version_of_rule_generator[/]*$', views.create_new_version_of_rule_generator, name='create_new_version_of_rule_generator'),
    url(r'^check_experiment_cloneable/(?P<experiment_id>\d+)[/]*$', views.check_experiment_cloneable),
    url(r'^clone_run/(?P<run_id>\d+)[/]*$', views.clone_run),
    url(r'^isatab/(?P<project_id>\w+)[/]$', ISATabExportView.as_view()),
    url(r'^isastudy/(?P<project_id>\w+)/(?P<experiment_id>\w+)[/]$', isa_study_view),
]
