from django.conf.urls import *
from django.conf import settings
from .views import CSVUploadViewFile, CSVUploadViewCaptureCSV
from .isatab import ISATabExportView, isa_study_view
from mastrms.decorators import mastr_users_only

urlpatterns = patterns('mastrms.repository.views',
    (r'^populate_select/(?P<model>\w+)/(?P<key>\w+)[/]*$', 'populate_select'),
    (r'^populate_select/(?P<model>\w+)/(?P<key>\w+)/(?P<value>\w+)[/]*$', 'populate_select'),
    (r'^populate_select/(?P<model>\w+)/(?P<key>\w+)/(?P<value>\w+)/(?P<field>\w+)/(?P<match>\w+)[/]*$', 'populate_select'),
    (r'^records/(?P<model>\w+)/(?P<field>\w+)/(?P<value>.+)[/]*$', 'records'),
    (r'^create/(?P<model>\w+)[/]*$', 'create_object'),
    (r'^createSamples[/]*$', 'create_samples'),
    (r'^batchcreate/samplelog[/]*$', 'batch_create_sample_logs'),
    (r'^update/(?P<model>\w+)/(?P<id>\w+)[/]*$', 'update_object'),
    (r'^delete/(?P<model>\w+)/(?P<id>\w+)[/]*$', 'delete_object'),
    (r'^associate/(?P<model>\w+)/(?P<association>\w+)/(?P<parent_id>\w+)/(?P<id>\w+)[/]*$', 'associate_object'),
    (r'^dissociate/(?P<model>\w+)/(?P<association>\w+)/(?P<parent_id>\w+)/(?P<id>\w+)[/]*$', 'dissociate_object'),
    (r'^recreate_sample_classes/(?P<experiment_id>\w+)[/]*$', 'recreate_sample_classes'),
    (r'^recordsProject/(?P<project_id>\w+)[/]*$', 'recordsProject'),
    (r'^recordsExperiments[/]*$', 'recordsExperiments'),
    (r'^recordsExperiments/(?P<project_id>\w+)[/]*$', 'recordsExperimentsForProject'),
    (r'^recordsRuns[/]*$', 'recordsRuns'),
    (r'^recordsRuleGenerators[/]*$', 'recordsRuleGenerators'),
    (r'^recordsRuleGeneratorsAccessibility[/]*$', 'recordsRuleGeneratorsAccessibility'),
    (r'^recordsRuleGeneratorsAccessibilityEnabled[/]*$', 'recordsRuleGeneratorsAccessibilityEnabled'),
    (r'^recordsSamplesForExperiment[/]*$', 'recordsSamplesForExperiment'),
    (r'^recordsSamplesForRun[/]*$', 'recordsSamplesForRun'),
    (r'^recordsMAStaff[/]*$', 'recordsMAStaff'),
    (r'^recordsClientList[/]*$', 'recordsClientList'),
    (r'^recordsClientFiles[/]*$', 'recordsClientFiles'),
    (r'^recordsSamples/experiment__id/(?P<experiment_id>\w+)[/]*$', 'recordsSamples'),
    (r'^recordsSamplesForClient/client/(?P<client>.+)[/]*$', 'recordsSamplesForClient'),
    (r'^recordsComponents[/]*$', 'recordsComponents'),
    (r'^recent_projects[/]*$', 'recent_projects'),
    (r'^recent_experiments[/]*$', 'recent_experiments'),
    (r'^recent_runs[/]*$', 'recent_runs'),
    (r'^sample_class_enable/(?P<id>\w+)[/]*$', 'sample_class_enable'),
    (r'^files[/]*$', 'experimentFilesList'),
    (r'^runFiles[/]*$', 'runFilesList'),
    (r'^moveFile[/]*$', 'moveFile'),
    (r'^deleteFile[/]*$', 'deleteFile'),
    (r'^uploadFile[/]*$', 'uploadFile'),
    (r'^newFolder[/]*$', 'newFolder'),
    (r'^uploadSampleCSV[/]*$', CSVUploadViewFile.as_view()),
    (r'^uploadRunCaptureCSV[/]*$', CSVUploadViewCaptureCSV.as_view()),
    (r'^packageFilesForDownload[/]*$', 'packageFilesForDownload'),
    (r'^downloadPackage[/]*$', 'downloadPackage'),
    (r'^downloadFile[/]*$', 'downloadFile'),
    (r'^downloadClientFile/(?P<filepath>.+)$', 'downloadClientFile'),
    (r'^downloadSOPFileById/(?P<sop_id>\w+)[/]*$', 'downloadSOPFileById'),
    url(r'^downloadSOPFile/(?P<sop_id>\w+)/(?P<filename>.*)[/]*$', 'downloadSOPFile', name='downloadSOPFile'),
    (r'^downloadRunFile[/]*$', 'downloadRunFile'),
    (r'^shareFile[/]*$', 'shareFile'),
    (r'^updateSingleSource/(?P<exp_id>\w+)[/]*$', 'update_single_source'),
    url(r'^generate_worklist/(?P<run_id>\w+)[/]*$', 'generate_worklist', name='generate_worklist'),
    url(r'^display_worklist/(?P<run_id>\w+)[/]*$', 'display_worklist', name='display_worklist'),
    url(r'^mark_run_complete/(?P<run_id>\w+)[/]*$', 'mark_run_complete', name='mark_run_complete'),
    url(r'^add_samples_to_run[/]*$', 'add_samples_to_run', name='add_samples_to_run'),
    url(r'^add_samples_to_class[/]*$', 'add_samples_to_class', name='add_samples_to_class'),
    url(r'^report_error[/]*$', 'report_error', name='report_error'),
    url(r'^remove_samples_from_run[/]*$', 'remove_samples_from_run', name='remove_samples_from_run'),
    url(r'^get_rule_generator[/]*$', 'get_rule_generator', name='get_rule_generator'),
    url(r'^create_rule_generator[/]*$', 'create_rule_generator', name='create_rule_generator'),
    url(r'^edit_rule_generator[/]*$', 'edit_rule_generator', name='edit_rule_generator'),
    url(r'^clone_rule_generator[/]*$', 'clone_rule_generator', name='clone_rule_generator'),
    url(r'^create_new_version_of_rule_generator[/]*$', 'create_new_version_of_rule_generator', name='create_new_version_of_rule_generator'),
    url(r'^check_experiment_cloneable/(?P<experiment_id>\d+)[/]*$', 'check_experiment_cloneable'),
    url(r'^clone_run/(?P<run_id>\d+)[/]*$', 'clone_run'),
    url(r'^isatab/(?P<project_id>\w+)[/]$', mastr_users_only(ISATabExportView.as_view())),
    url(r'^isastudy/(?P<project_id>\w+)/(?P<experiment_id>\w+)[/]$', isa_study_view),
)
