#!/usr/bin/env python

from django.utils.crypto import get_random_string


def print_secret_key():
    "Prints a new random secret key"
    chars = 'abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)'
    print get_random_string(50, chars)

if __name__ == '__main__':
    print_secret_key()
