#Identifiers used in main window
ID_TEST_CONNECTION = 101
ID_CHECK_NOW = 102
ID_MINIMISE = 103
ID_QUIT = 104
ID_PREFERENCES = 201
ID_PYCRUST = 202

#Preferences window
ID_NODESELECTOR_DIALOG = 204
ID_CHOOSENODE_BUTTON = 205
ID_SENDLOGS_BUTTON = 206
ID_SENDKEY_BUTTON = 207
ID_GENERATEFILES_BUTTON = 208 #in the simulator application
ID_CLEARINPUT_BUTTON = 209 #in the simulator application
#Node config selector window


