#!/bin/sh

set -e
#set -x

. /usr/share/debconf/confmodule

mastrms_config_get() {
    KEY="$1"
    DEFAULT="$2"
    GREPRESULT=$(grep $KEY /etc/mastr-ms/mastr-ms.conf 2>&1)
    if [ $? -ne 0 ] ; then
        echo "$DEFAULT"
    else
        echo "$GREPRESULT" | tail -n 1 | perl -n -e"/$KEY[ ]*=[ ]*(.*)/ && print \"\$1\n\""
    fi
}

# load config file
SELF_URL_PATH=$(mastrms_config_get "SELF_URL_PATH" "http://example.org/mastr-ms/")
db_set mastr-ms/self_url_path "$SELF_URL_PATH"

SECRET_KEY=$(mastrms_config_get "SECRET_KEY" "changeme")
if [ "$SECRET_KEY" = "changeme" ]; then
    SECRET_KEY=$(/usr/share/python/mastr-ms/bin/gen-secret-key)
fi
db_set mastr-ms/secret_key "$SECRET_KEY"

if [ -f /usr/share/dbconfig-common/dpkg/config ]; then
    dbc_dbtypes="pgsql"
    dbc_authmethod_user="password"
    . /usr/share/dbconfig-common/dpkg/config
    dbc_go mastr-ms $@
fi

# questions
db_input high mastr-ms/reconfigure-webserver || true
db_input high mastr-ms/self_url_path || true
db_input low mastr-ms/secret_key || true
db_go || true
db_input high mastr-ms/restart-webserver || true
db_go || true
