Document: mastr-ms
Title: Debian mastr-ms Manual
Author: <insert document author here>
Abstract: This manual describes what mastr-ms is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mastr-ms/mastr-ms.sgml.gz

Format: postscript
Files: /usr/share/doc/mastr-ms/mastr-ms.ps.gz

Format: text
Files: /usr/share/doc/mastr-ms/mastr-ms.text.gz

Format: HTML
Index: /usr/share/doc/mastr-ms/html/index.html
Files: /usr/share/doc/mastr-ms/html/*.html
