#!/bin/sh

set -e
#set -x

lighttpd_remove() {
    if which lighty-disable-mod >/dev/null 2>&1 ; then
        lighty-disable-mod mastr-ms || true
    fi
    if [ -L /etc/lighttpd/conf-enabled/50-mastr-ms.conf ] ; then
        rm /etc/lighttpd/conf-enabled/50-mastr-ms.conf
    fi
}

apache_remove() {
    if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
        apache2_invoke disconf mastr-ms
    elif  dpkg-query -f '${Version}'  -W 'apache2.2-common' > /dev/null 2>&1 ; then
        if [ -L /etc/apache2/conf.d/mastr-ms.conf ] ; then
            rm /etc/apache2/conf.d/mastr-ms.conf
        fi
    fi
}

if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
    . /usr/share/apache2/apache2-maintscript-helper
fi

if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
fi

if [ -f /usr/share/dbconfig-common/dpkg/postrm ]; then
    . /usr/share/dbconfig-common/dpkg/postrm
    dbc_go mastr-ms $@
fi

if [ "$1" = "purge" ]; then
    rm -rf /etc/mastr-ms

    dpkg-statoverride --remove /var/cache/mastr-ms || true
    dpkg-statoverride --remove /var/log/mastr-ms || true
    dpkg-statoverride --remove /var/cache/mastr-ms/upload || true
    dpkg-statoverride --remove /var/cache/mastr-ms/static || true
    dpkg-statoverride --remove /var/cache/mastr-ms/scratch || true

    if (which deluser && getent passwd mastr-ms) > /dev/null 2>&1; then
        deluser --system --quiet --backup-to /var/lib mastr-ms
    fi
    if (which delgroup && getent group mastr-ms) > /dev/null 2>&1; then
        delgroup --system --quiet mastr-ms
    fi
fi

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    rm -rf /var/cache/mastr-ms/static
fi

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    if [ -f /usr/share/debconf/confmodule ]; then
        db_get mastr-ms/reconfigure-webserver || true
        webservers="$RET"
        db_get mastr-ms/restart-webserver || true
        restart="$RET"

        # db_stop means no more db_gets can be run after here
        # db_stop || true

        for webserver in $webservers; do
            webserver=${webserver%,}
            if [ "$webserver" = "lighttpd" ]; then
                lighttpd_remove
            elif [ "$webserver" = "apache2" ]; then
                apache_remove
            fi

            if [ "$res" = "true" ]; then
                # Redirection of 3 is needed because Debconf uses it and it might 
                # be inherited by webserver. See bug #446324.
                if [ -x /usr/sbin/invoke-rc.d ]; then
                    invoke-rc.d $webserver reload 3>/dev/null || true
                else
                    /etc/init.d/$webserver reload 3>/dev/null || true
                fi
            fi
        done
    fi
fi

if [ "$1" = "purge" ]; then
    rm -f /etc/mastr-ms/database.conf
    if which ucf >/dev/null 2>&1; then
     	ucf --purge /etc/mastr-ms/database.conf
    fi
fi

#DEBHELPER#
